import SwiftUI

// GENERATED from the Expo app's `lib/data/nutrients.ts`, `lib/data/fr/nutrients.ts`,
// `lib/data/macro-education.ts` and `lib/data/fr/macro-education.ts` — the words members read on the
// micronutrient and macro pages, in both languages. Regenerate with the script recorded in the session
// handoff (STUDIO `.context/agents/2026-09-03_ios-testflight-auth-food.md`); do not edit by hand.
// RDA values are duplicated from `MicroCoverage.nutrients` on purpose and a test keeps them equal.

/// The 21 tracked micronutrients in their three groups, with the copy each page shows.
enum NutrientCatalog {
    enum GroupKey: String, CaseIterable, Sendable {
        case vitamins, minerals
        case fattyAcids = "fatty_acids"
    }

    struct Group: Identifiable, Sendable {
        let key: GroupKey
        let name: String
        let emoji: String
        let description: String
        let whyItMatters: String
        let topFoods: String
        let colorHex: UInt32
        var id: String { key.rawValue }
        var color: Color { Color(hex: colorHex) }
    }

    struct FoodSource: Sendable, Hashable {
        let food: String
        let amount: String
        let emoji: String
    }

    struct Nutrient: Identifiable, Sendable {
        let key: String
        let name: String
        let groupKey: GroupKey
        let emoji: String
        let unit: String
        let tagline: String
        let description: String
        let rdaMale: Double
        let rdaFemale: Double
        let foodSources: [FoodSource]
        /// Onboarding complaint keys (`symptomLabel`).
        let deficiencySymptoms: [String]
        var id: String { key }
        /// Female targets when sex is unknown — the web default.
        func target(sex: MemberProfile.Sex?) -> Double { sex == .male ? rdaMale : rdaFemale }
    }

    static var groups: [Group] {
        [
            Group(key: .vitamins, name: String(localized: "nutrientGroup.vitamins.name", defaultValue: "Vitamins"), emoji: "💊", description: String(localized: "nutrientGroup.vitamins.description", defaultValue: "Organic compounds essential for growth, energy metabolism, immune function, and cellular repair. Most cannot be synthesised by the body · they must come from food."), whyItMatters: String(localized: "nutrientGroup.vitamins.why", defaultValue: "Vitamins act as cofactors in hundreds of enzymatic reactions. Even subclinical deficiencies can cause fatigue, poor immunity, skin issues, and neurological symptoms long before clinical signs appear."), topFoods: String(localized: "nutrientGroup.vitamins.foods", defaultValue: "Leafy greens, organ meats, fish, eggs, citrus, fortified foods, sunlight (D3)"), colorHex: 0x7C3AED),
            Group(key: .minerals, name: String(localized: "nutrientGroup.minerals.name", defaultValue: "Minerals"), emoji: "⚡", description: String(localized: "nutrientGroup.minerals.description", defaultValue: "Inorganic elements required for bone structure, nerve transmission, fluid balance, enzyme function, and oxygen transport. Unlike vitamins, they cannot be created or broken down."), whyItMatters: String(localized: "nutrientGroup.minerals.why", defaultValue: "Mineral deficiencies are among the most common nutritional issues in modern diets. Magnesium alone is involved in 300+ enzymatic reactions · low levels are linked to fatigue, muscle cramps, anxiety, and poor sleep."), topFoods: String(localized: "nutrientGroup.minerals.foods", defaultValue: "Nuts, seeds, legumes, leafy greens, seafood, dairy, whole grains"), colorHex: 0x0369A1),
            Group(key: .fattyAcids, name: String(localized: "nutrientGroup.fatty_acids.name", defaultValue: "Essential Fatty Acids"), emoji: "🐟", description: String(localized: "nutrientGroup.fatty_acids.description", defaultValue: "Polyunsaturated fats that the body cannot produce on its own. Omega-3 (anti-inflammatory) and Omega-6 (pro-inflammatory) must be consumed in the right ratio · ideally 1:4 or less."), whyItMatters: String(localized: "nutrientGroup.fatty_acids.why", defaultValue: "Modern diets often skew 1:20 or worse Omega-3:Omega-6. This chronic imbalance drives systemic inflammation, poor cardiovascular health, brain fog, and mood instability."), topFoods: String(localized: "nutrientGroup.fatty_acids.foods", defaultValue: "Fatty fish (salmon, sardines, mackerel), walnuts, flaxseeds, chia seeds"), colorHex: 0xE2C25C),
        ]
    }

    static var nutrients: [Nutrient] {
        [
            Nutrient(key: "vitamin_d3", name: String(localized: "nutrient.vitamin_d3.name", defaultValue: "Vitamin D3"), groupKey: .vitamins, emoji: "☀️", unit: "mcg", tagline: String(localized: "nutrient.vitamin_d3.tagline", defaultValue: "The sunshine vitamin"), description: String(localized: "nutrient.vitamin_d3.description", defaultValue: "Vitamin D3 functions as a hormone, regulating calcium absorption, immune function, mood, and gene expression. Up to 80% of European adults are deficient, especially in winter."), rdaMale: 50, rdaFemale: 50, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_d3.food.0", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.vitamin_d3.amount.0", defaultValue: "14 mcg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.vitamin_d3.food.1", defaultValue: "Sardines (90g)"), amount: String(localized: "nutrient.vitamin_d3.amount.1", defaultValue: "9 mcg"), emoji: "🐠"), FoodSource(food: String(localized: "nutrient.vitamin_d3.food.2", defaultValue: "Egg yolk (1)"), amount: String(localized: "nutrient.vitamin_d3.amount.2", defaultValue: "1.1 mcg"), emoji: "🥚"), FoodSource(food: String(localized: "nutrient.vitamin_d3.food.3", defaultValue: "Fortified milk (1 cup)"), amount: String(localized: "nutrient.vitamin_d3.amount.3", defaultValue: "3 mcg"), emoji: "🥛")], deficiencySymptoms: ["fatigue", "mood_swings", "joint_pain", "anxiety", "insomnia"]),
            Nutrient(key: "vitamin_c", name: String(localized: "nutrient.vitamin_c.name", defaultValue: "Vitamin C"), groupKey: .vitamins, emoji: "🍊", unit: "mg", tagline: String(localized: "nutrient.vitamin_c.tagline", defaultValue: "Master antioxidant"), description: String(localized: "nutrient.vitamin_c.description", defaultValue: "Essential for collagen synthesis, iron absorption, immune defence, and neutralising free radicals. The body excretes excess daily, so consistent intake is needed."), rdaMale: 90, rdaFemale: 75, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_c.food.0", defaultValue: "Red bell pepper (80g)"), amount: String(localized: "nutrient.vitamin_c.amount.0", defaultValue: "95mg"), emoji: "🫑"), FoodSource(food: String(localized: "nutrient.vitamin_c.food.1", defaultValue: "Kiwi (1 fruit, 70g)"), amount: String(localized: "nutrient.vitamin_c.amount.1", defaultValue: "72mg"), emoji: "🥝"), FoodSource(food: String(localized: "nutrient.vitamin_c.food.2", defaultValue: "Orange (1 medium, 130g)"), amount: String(localized: "nutrient.vitamin_c.amount.2", defaultValue: "70mg"), emoji: "🍊"), FoodSource(food: String(localized: "nutrient.vitamin_c.food.3", defaultValue: "Broccoli (80g cooked)"), amount: String(localized: "nutrient.vitamin_c.amount.3", defaultValue: "51mg"), emoji: "🥦")], deficiencySymptoms: ["fatigue", "skin_issues", "joint_pain"]),
            Nutrient(key: "vitamin_b12", name: String(localized: "nutrient.vitamin_b12.name", defaultValue: "Vitamin B12"), groupKey: .vitamins, emoji: "⚡", unit: "mcg", tagline: String(localized: "nutrient.vitamin_b12.tagline", defaultValue: "Nerve & energy vitamin"), description: String(localized: "nutrient.vitamin_b12.description", defaultValue: "Critical for red blood cell formation, DNA synthesis, and nervous system function. Vegans and vegetarians are at high risk of deficiency. Absorption declines with age."), rdaMale: 2.4, rdaFemale: 2.4, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_b12.food.0", defaultValue: "Beef liver (85g)"), amount: String(localized: "nutrient.vitamin_b12.amount.0", defaultValue: "70mcg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.vitamin_b12.food.1", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.vitamin_b12.amount.1", defaultValue: "4.9mcg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.vitamin_b12.food.2", defaultValue: "Eggs (2 large, 100g)"), amount: String(localized: "nutrient.vitamin_b12.amount.2", defaultValue: "1.4mcg"), emoji: "🥚"), FoodSource(food: String(localized: "nutrient.vitamin_b12.food.3", defaultValue: "Greek yogurt (1 cup, 245g)"), amount: String(localized: "nutrient.vitamin_b12.amount.3", defaultValue: "1.3mcg"), emoji: "🫙")], deficiencySymptoms: ["fatigue", "brain_fog", "mood_swings", "anxiety"]),
            Nutrient(key: "folate", name: String(localized: "nutrient.folate.name", defaultValue: "Folate (B9)"), groupKey: .vitamins, emoji: "🌿", unit: "mcg DFE", tagline: String(localized: "nutrient.folate.tagline", defaultValue: "Cell & DNA builder"), description: String(localized: "nutrient.folate.description", defaultValue: "Folate is essential for DNA replication, cell division, amino acid metabolism, and methylation reactions. Critical during pregnancy and for anyone with MTHFR variants."), rdaMale: 400, rdaFemale: 400, foodSources: [FoodSource(food: String(localized: "nutrient.folate.food.0", defaultValue: "Spinach (180g cooked)"), amount: String(localized: "nutrient.folate.amount.0", defaultValue: "263mcg"), emoji: "🥬"), FoodSource(food: String(localized: "nutrient.folate.food.1", defaultValue: "Lentils (100g cooked)"), amount: String(localized: "nutrient.folate.amount.1", defaultValue: "179mcg"), emoji: "🫘"), FoodSource(food: String(localized: "nutrient.folate.food.2", defaultValue: "Asparagus (6 spears, 90g)"), amount: String(localized: "nutrient.folate.amount.2", defaultValue: "134mcg"), emoji: "🌿"), FoodSource(food: String(localized: "nutrient.folate.food.3", defaultValue: "Avocado (½, 70g)"), amount: String(localized: "nutrient.folate.amount.3", defaultValue: "82mcg"), emoji: "🥑")], deficiencySymptoms: ["fatigue", "brain_fog", "mood_swings"]),
            Nutrient(key: "vitamin_a", name: String(localized: "nutrient.vitamin_a.name", defaultValue: "Vitamin A"), groupKey: .vitamins, emoji: "🥕", unit: "mcg RAE", tagline: String(localized: "nutrient.vitamin_a.tagline", defaultValue: "Vision & immune function"), description: String(localized: "nutrient.vitamin_a.description", defaultValue: "Vitamin A supports night vision, skin integrity, immune barriers, and cell differentiation. It exists as preformed (animal sources) and beta-carotene (plant sources)."), rdaMale: 900, rdaFemale: 700, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_a.food.0", defaultValue: "Sweet potato (1 medium, 130g)"), amount: String(localized: "nutrient.vitamin_a.amount.0", defaultValue: "1096mcg"), emoji: "🍠"), FoodSource(food: String(localized: "nutrient.vitamin_a.food.1", defaultValue: "Carrots (80g)"), amount: String(localized: "nutrient.vitamin_a.amount.1", defaultValue: "459mcg"), emoji: "🥕"), FoodSource(food: String(localized: "nutrient.vitamin_a.food.2", defaultValue: "Beef liver (85g)"), amount: String(localized: "nutrient.vitamin_a.amount.2", defaultValue: "6582mcg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.vitamin_a.food.3", defaultValue: "Spinach (90g cooked)"), amount: String(localized: "nutrient.vitamin_a.amount.3", defaultValue: "472mcg"), emoji: "🥬")], deficiencySymptoms: ["skin_issues", "fatigue"]),
            Nutrient(key: "vitamin_k2", name: String(localized: "nutrient.vitamin_k2.name", defaultValue: "Vitamin K2"), groupKey: .vitamins, emoji: "🫀", unit: "mcg", tagline: String(localized: "nutrient.vitamin_k2.tagline", defaultValue: "Calcium director"), description: String(localized: "nutrient.vitamin_k2.description", defaultValue: "K2 activates proteins that direct calcium to bones (not arteries). Often deficient in Western diets. Works synergistically with D3 · both are needed together."), rdaMale: 120, rdaFemale: 90, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_k2.food.0", defaultValue: "Natto (45g)"), amount: String(localized: "nutrient.vitamin_k2.amount.0", defaultValue: "500mcg"), emoji: "🫘"), FoodSource(food: String(localized: "nutrient.vitamin_k2.food.1", defaultValue: "Gouda cheese (30g)"), amount: String(localized: "nutrient.vitamin_k2.amount.1", defaultValue: "76mcg"), emoji: "🧀"), FoodSource(food: String(localized: "nutrient.vitamin_k2.food.2", defaultValue: "Egg yolks (2, 34g)"), amount: String(localized: "nutrient.vitamin_k2.amount.2", defaultValue: "32mcg"), emoji: "🥚"), FoodSource(food: String(localized: "nutrient.vitamin_k2.food.3", defaultValue: "Pasture butter (15g)"), amount: String(localized: "nutrient.vitamin_k2.amount.3", defaultValue: "15mcg"), emoji: "🧈")], deficiencySymptoms: ["joint_pain"]),
            Nutrient(key: "vitamin_e", name: String(localized: "nutrient.vitamin_e.name", defaultValue: "Vitamin E"), groupKey: .vitamins, emoji: "🌻", unit: "mg", tagline: String(localized: "nutrient.vitamin_e.tagline", defaultValue: "Cell-protecting antioxidant"), description: String(localized: "nutrient.vitamin_e.description", defaultValue: "Vitamin E is a fat-soluble antioxidant that protects cell membranes from oxidative damage. It supports immune function, skin health, and cardiovascular protection. Works synergistically with Vitamin C."), rdaMale: 15, rdaFemale: 15, foodSources: [FoodSource(food: String(localized: "nutrient.vitamin_e.food.0", defaultValue: "Sunflower seeds (30g)"), amount: String(localized: "nutrient.vitamin_e.amount.0", defaultValue: "10mg"), emoji: "🌻"), FoodSource(food: String(localized: "nutrient.vitamin_e.food.1", defaultValue: "Almonds (30g)"), amount: String(localized: "nutrient.vitamin_e.amount.1", defaultValue: "7.3mg"), emoji: "🥜"), FoodSource(food: String(localized: "nutrient.vitamin_e.food.2", defaultValue: "Avocado (½, 70g)"), amount: String(localized: "nutrient.vitamin_e.amount.2", defaultValue: "2.1mg"), emoji: "🥑"), FoodSource(food: String(localized: "nutrient.vitamin_e.food.3", defaultValue: "Spinach (180g cooked)"), amount: String(localized: "nutrient.vitamin_e.amount.3", defaultValue: "3.7mg"), emoji: "🥬")], deficiencySymptoms: ["fatigue", "skin_issues"]),
            Nutrient(key: "biotin", name: String(localized: "nutrient.biotin.name", defaultValue: "Biotin (B7)"), groupKey: .vitamins, emoji: "💅", unit: "mcg", tagline: String(localized: "nutrient.biotin.tagline", defaultValue: "Hair, skin & metabolism"), description: String(localized: "nutrient.biotin.description", defaultValue: "Biotin is a B-vitamin cofactor in carboxylase enzymes involved in fatty acid synthesis, gluconeogenesis, and amino acid metabolism. Widely known for supporting hair, skin, and nail health."), rdaMale: 30, rdaFemale: 30, foodSources: [FoodSource(food: String(localized: "nutrient.biotin.food.0", defaultValue: "Beef liver (85g)"), amount: String(localized: "nutrient.biotin.amount.0", defaultValue: "35mcg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.biotin.food.1", defaultValue: "Eggs (2 large, 100g)"), amount: String(localized: "nutrient.biotin.amount.1", defaultValue: "20mcg"), emoji: "🥚"), FoodSource(food: String(localized: "nutrient.biotin.food.2", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.biotin.amount.2", defaultValue: "5mcg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.biotin.food.3", defaultValue: "Sweet potato (1 medium, 130g)"), amount: String(localized: "nutrient.biotin.amount.3", defaultValue: "4.8mcg"), emoji: "🍠")], deficiencySymptoms: ["skin_issues", "fatigue"]),
            Nutrient(key: "magnesium", name: String(localized: "nutrient.magnesium.name", defaultValue: "Magnesium"), groupKey: .minerals, emoji: "💪", unit: "mg", tagline: String(localized: "nutrient.magnesium.tagline", defaultValue: "Master mineral · 300+ reactions"), description: String(localized: "nutrient.magnesium.description", defaultValue: "Magnesium is a cofactor in over 300 enzymatic reactions, including energy production, protein synthesis, muscle contraction, and nerve function. About 50% of people are deficient."), rdaMale: 420, rdaFemale: 320, foodSources: [FoodSource(food: String(localized: "nutrient.magnesium.food.0", defaultValue: "Spinach (180g cooked)"), amount: String(localized: "nutrient.magnesium.amount.0", defaultValue: "157mg"), emoji: "🥬"), FoodSource(food: String(localized: "nutrient.magnesium.food.1", defaultValue: "Pumpkin seeds (30g)"), amount: String(localized: "nutrient.magnesium.amount.1", defaultValue: "156mg"), emoji: "🎃"), FoodSource(food: String(localized: "nutrient.magnesium.food.2", defaultValue: "Dark chocolate (30g)"), amount: String(localized: "nutrient.magnesium.amount.2", defaultValue: "64mg"), emoji: "🍫"), FoodSource(food: String(localized: "nutrient.magnesium.food.3", defaultValue: "Black beans (85g cooked)"), amount: String(localized: "nutrient.magnesium.amount.3", defaultValue: "60mg"), emoji: "🫘")], deficiencySymptoms: ["fatigue", "insomnia", "anxiety", "headaches", "muscle_pain"]),
            Nutrient(key: "iron", name: String(localized: "nutrient.iron.name", defaultValue: "Iron"), groupKey: .minerals, emoji: "🩸", unit: "mg", tagline: String(localized: "nutrient.iron.tagline", defaultValue: "Oxygen transporter"), description: String(localized: "nutrient.iron.description", defaultValue: "Iron forms haemoglobin to carry oxygen through the body. Iron deficiency is the world's most common nutritional deficiency · women are particularly at risk. Heme iron (meat) absorbs 2-3x better than non-heme (plants)."), rdaMale: 8, rdaFemale: 18, foodSources: [FoodSource(food: String(localized: "nutrient.iron.food.0", defaultValue: "Beef liver (85g)"), amount: String(localized: "nutrient.iron.amount.0", defaultValue: "5.8mg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.iron.food.1", defaultValue: "Lentils (100g cooked)"), amount: String(localized: "nutrient.iron.amount.1", defaultValue: "3.3mg"), emoji: "🫘"), FoodSource(food: String(localized: "nutrient.iron.food.2", defaultValue: "Spinach (180g cooked)"), amount: String(localized: "nutrient.iron.amount.2", defaultValue: "3.2mg"), emoji: "🥬"), FoodSource(food: String(localized: "nutrient.iron.food.3", defaultValue: "Dark chocolate (30g)"), amount: String(localized: "nutrient.iron.amount.3", defaultValue: "3.4mg"), emoji: "🍫")], deficiencySymptoms: ["fatigue", "brain_fog"]),
            Nutrient(key: "zinc", name: String(localized: "nutrient.zinc.name", defaultValue: "Zinc"), groupKey: .minerals, emoji: "🔷", unit: "mg", tagline: String(localized: "nutrient.zinc.tagline", defaultValue: "Immune & hormone support"), description: String(localized: "nutrient.zinc.description", defaultValue: "Zinc is essential for immune function, wound healing, protein synthesis, DNA repair, and testosterone production. Depleted rapidly during stress or illness."), rdaMale: 11, rdaFemale: 8, foodSources: [FoodSource(food: String(localized: "nutrient.zinc.food.0", defaultValue: "Oysters (85g)"), amount: String(localized: "nutrient.zinc.amount.0", defaultValue: "74mg"), emoji: "🦪"), FoodSource(food: String(localized: "nutrient.zinc.food.1", defaultValue: "Beef (85g)"), amount: String(localized: "nutrient.zinc.amount.1", defaultValue: "7mg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.zinc.food.2", defaultValue: "Pumpkin seeds (30g)"), amount: String(localized: "nutrient.zinc.amount.2", defaultValue: "2.2mg"), emoji: "🎃"), FoodSource(food: String(localized: "nutrient.zinc.food.3", defaultValue: "Chickpeas (85g cooked)"), amount: String(localized: "nutrient.zinc.amount.3", defaultValue: "1.3mg"), emoji: "🫘")], deficiencySymptoms: ["skin_issues", "fatigue", "digestive"]),
            Nutrient(key: "calcium", name: String(localized: "nutrient.calcium.name", defaultValue: "Calcium"), groupKey: .minerals, emoji: "🦴", unit: "mg", tagline: String(localized: "nutrient.calcium.tagline", defaultValue: "Bones, nerves & muscles"), description: String(localized: "nutrient.calcium.description", defaultValue: "The most abundant mineral in the body · 99% stored in bones and teeth. Also critical for nerve transmission, muscle contraction, and blood clotting. Requires K2 and D3 for proper utilisation."), rdaMale: 1000, rdaFemale: 1000, foodSources: [FoodSource(food: String(localized: "nutrient.calcium.food.0", defaultValue: "Greek yogurt (1 cup, 245g)"), amount: String(localized: "nutrient.calcium.amount.0", defaultValue: "250mg"), emoji: "🫙"), FoodSource(food: String(localized: "nutrient.calcium.food.1", defaultValue: "Sardines with bones (85g)"), amount: String(localized: "nutrient.calcium.amount.1", defaultValue: "325mg"), emoji: "🐠"), FoodSource(food: String(localized: "nutrient.calcium.food.2", defaultValue: "Kale (130g cooked)"), amount: String(localized: "nutrient.calcium.amount.2", defaultValue: "177mg"), emoji: "🥬"), FoodSource(food: String(localized: "nutrient.calcium.food.3", defaultValue: "Cheddar cheese (30g)"), amount: String(localized: "nutrient.calcium.amount.3", defaultValue: "204mg"), emoji: "🧀")], deficiencySymptoms: ["muscle_pain", "insomnia"]),
            Nutrient(key: "selenium", name: String(localized: "nutrient.selenium.name", defaultValue: "Selenium"), groupKey: .minerals, emoji: "🛡️", unit: "mcg", tagline: String(localized: "nutrient.selenium.tagline", defaultValue: "Antioxidant & thyroid"), description: String(localized: "nutrient.selenium.description", defaultValue: "Selenium is a component of powerful antioxidant enzymes and is essential for thyroid hormone synthesis and conversion (T4→T3). The EU population is often mildly deficient."), rdaMale: 55, rdaFemale: 55, foodSources: [FoodSource(food: String(localized: "nutrient.selenium.food.0", defaultValue: "Brazil nuts (2 nuts, 8g)"), amount: String(localized: "nutrient.selenium.amount.0", defaultValue: "80mcg"), emoji: "🥜"), FoodSource(food: String(localized: "nutrient.selenium.food.1", defaultValue: "Tuna (85g)"), amount: String(localized: "nutrient.selenium.amount.1", defaultValue: "92mcg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.selenium.food.2", defaultValue: "Turkey breast (85g)"), amount: String(localized: "nutrient.selenium.amount.2", defaultValue: "27mcg"), emoji: "🦃"), FoodSource(food: String(localized: "nutrient.selenium.food.3", defaultValue: "Eggs (2 large, 100g)"), amount: String(localized: "nutrient.selenium.amount.3", defaultValue: "28mcg"), emoji: "🥚")], deficiencySymptoms: ["fatigue", "brain_fog"]),
            Nutrient(key: "iodine", name: String(localized: "nutrient.iodine.name", defaultValue: "Iodine"), groupKey: .minerals, emoji: "🦋", unit: "mcg", tagline: String(localized: "nutrient.iodine.tagline", defaultValue: "Thyroid health essential"), description: String(localized: "nutrient.iodine.description", defaultValue: "Iodine is required for thyroid hormone production (T3 and T4), which controls metabolism, temperature, heart rate, and energy. Deficiency is a leading cause of hypothyroidism."), rdaMale: 150, rdaFemale: 150, foodSources: [FoodSource(food: String(localized: "nutrient.iodine.food.0", defaultValue: "Nori seaweed (1 sheet, 3g)"), amount: String(localized: "nutrient.iodine.amount.0", defaultValue: "50mcg"), emoji: "🌿"), FoodSource(food: String(localized: "nutrient.iodine.food.1", defaultValue: "Cod (85g)"), amount: String(localized: "nutrient.iodine.amount.1", defaultValue: "99mcg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.iodine.food.2", defaultValue: "Plain yogurt (1 cup, 245g)"), amount: String(localized: "nutrient.iodine.amount.2", defaultValue: "75mcg"), emoji: "🫙"), FoodSource(food: String(localized: "nutrient.iodine.food.3", defaultValue: "Iodised salt (1.5g)"), amount: String(localized: "nutrient.iodine.amount.3", defaultValue: "71mcg"), emoji: "🧂")], deficiencySymptoms: ["fatigue", "brain_fog", "mood_swings"]),
            Nutrient(key: "potassium", name: String(localized: "nutrient.potassium.name", defaultValue: "Potassium"), groupKey: .minerals, emoji: "🍌", unit: "mg", tagline: String(localized: "nutrient.potassium.tagline", defaultValue: "Heart & fluid balance"), description: String(localized: "nutrient.potassium.description", defaultValue: "Potassium maintains fluid balance, nerve signals, muscle contractions, and blood pressure. Most people get far less than the 3,500mg daily recommendation."), rdaMale: 3400, rdaFemale: 2600, foodSources: [FoodSource(food: String(localized: "nutrient.potassium.food.0", defaultValue: "Avocado (1 medium, 150g)"), amount: String(localized: "nutrient.potassium.amount.0", defaultValue: "975mg"), emoji: "🥑"), FoodSource(food: String(localized: "nutrient.potassium.food.1", defaultValue: "Sweet potato (1 medium, 130g)"), amount: String(localized: "nutrient.potassium.amount.1", defaultValue: "542mg"), emoji: "🍠"), FoodSource(food: String(localized: "nutrient.potassium.food.2", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.potassium.amount.2", defaultValue: "534mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.potassium.food.3", defaultValue: "Spinach (180g cooked)"), amount: String(localized: "nutrient.potassium.amount.3", defaultValue: "839mg"), emoji: "🥬")], deficiencySymptoms: ["fatigue", "muscle_pain"]),
            Nutrient(key: "phosphorus", name: String(localized: "nutrient.phosphorus.name", defaultValue: "Phosphorus"), groupKey: .minerals, emoji: "🔬", unit: "mg", tagline: String(localized: "nutrient.phosphorus.tagline", defaultValue: "Bone builder & energy currency"), description: String(localized: "nutrient.phosphorus.description", defaultValue: "Phosphorus is the second most abundant mineral in the body. It forms the backbone of DNA and ATP (cellular energy), builds bones alongside calcium, and buffers blood pH. Deficiency is rare but can occur with excessive antacid use."), rdaMale: 700, rdaFemale: 700, foodSources: [FoodSource(food: String(localized: "nutrient.phosphorus.food.0", defaultValue: "Pumpkin seeds (30g)"), amount: String(localized: "nutrient.phosphorus.amount.0", defaultValue: "332mg"), emoji: "🎃"), FoodSource(food: String(localized: "nutrient.phosphorus.food.1", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.phosphorus.amount.1", defaultValue: "214mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.phosphorus.food.2", defaultValue: "Lentils (100g cooked)"), amount: String(localized: "nutrient.phosphorus.amount.2", defaultValue: "178mg"), emoji: "🫘"), FoodSource(food: String(localized: "nutrient.phosphorus.food.3", defaultValue: "Greek yogurt (1 cup, 245g)"), amount: String(localized: "nutrient.phosphorus.amount.3", defaultValue: "220mg"), emoji: "🫙")], deficiencySymptoms: ["fatigue", "muscle_pain", "joint_pain"]),
            Nutrient(key: "omega3", name: String(localized: "nutrient.omega3.name", defaultValue: "Omega-3 (EPA + DHA)"), groupKey: .fattyAcids, emoji: "🐟", unit: "g", tagline: String(localized: "nutrient.omega3.tagline", defaultValue: "Anti-inflammatory foundation"), description: String(localized: "nutrient.omega3.description", defaultValue: "EPA and DHA are the active forms of Omega-3 · found primarily in fatty fish. EPA reduces inflammation, DHA supports brain structure and function. Conversion from ALA (plant sources) is only 5-10% efficient."), rdaMale: 1.6, rdaFemale: 1.1, foodSources: [FoodSource(food: String(localized: "nutrient.omega3.food.0", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.omega3.amount.0", defaultValue: "1800mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.omega3.food.1", defaultValue: "Sardines (85g)"), amount: String(localized: "nutrient.omega3.amount.1", defaultValue: "1480mg"), emoji: "🐠"), FoodSource(food: String(localized: "nutrient.omega3.food.2", defaultValue: "Mackerel (85g)"), amount: String(localized: "nutrient.omega3.amount.2", defaultValue: "2200mg"), emoji: "🐡"), FoodSource(food: String(localized: "nutrient.omega3.food.3", defaultValue: "Anchovies (30g)"), amount: String(localized: "nutrient.omega3.amount.3", defaultValue: "750mg"), emoji: "🐟")], deficiencySymptoms: ["brain_fog", "joint_pain", "mood_swings", "skin_issues"]),
            Nutrient(key: "ala", name: String(localized: "nutrient.ala.name", defaultValue: "ALA (Omega-3)"), groupKey: .fattyAcids, emoji: "🌱", unit: "g", tagline: String(localized: "nutrient.ala.tagline", defaultValue: "Plant-based Omega-3"), description: String(localized: "nutrient.ala.description", defaultValue: "Alpha-linolenic acid is the plant form of Omega-3. The body can convert it to EPA/DHA, but inefficiently. Still valuable for overall Omega-3 ratio improvement."), rdaMale: 1.6, rdaFemale: 1.1, foodSources: [FoodSource(food: String(localized: "nutrient.ala.food.0", defaultValue: "Chia seeds (1 tbsp, 12g)"), amount: String(localized: "nutrient.ala.amount.0", defaultValue: "2.5g"), emoji: "🌱"), FoodSource(food: String(localized: "nutrient.ala.food.1", defaultValue: "Walnuts (30g)"), amount: String(localized: "nutrient.ala.amount.1", defaultValue: "2.6g"), emoji: "🥜"), FoodSource(food: String(localized: "nutrient.ala.food.2", defaultValue: "Flaxseed (1 tbsp, 10g)"), amount: String(localized: "nutrient.ala.amount.2", defaultValue: "2.4g"), emoji: "🌾"), FoodSource(food: String(localized: "nutrient.ala.food.3", defaultValue: "Hemp seeds (30g)"), amount: String(localized: "nutrient.ala.amount.3", defaultValue: "3g"), emoji: "🌿")], deficiencySymptoms: ["brain_fog", "mood_swings"]),
            Nutrient(key: "epa", name: String(localized: "nutrient.epa.name", defaultValue: "EPA (Omega-3)"), groupKey: .fattyAcids, emoji: "🔥", unit: "mg", tagline: String(localized: "nutrient.epa.tagline", defaultValue: "Anti-inflammatory omega-3"), description: String(localized: "nutrient.epa.description", defaultValue: "Eicosapentaenoic acid (EPA) is the primary anti-inflammatory omega-3 fatty acid. It competes with arachidonic acid (omega-6) to reduce pro-inflammatory eicosanoid production. Found almost exclusively in marine sources."), rdaMale: 500, rdaFemale: 500, foodSources: [FoodSource(food: String(localized: "nutrient.epa.food.0", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.epa.amount.0", defaultValue: "730mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.epa.food.1", defaultValue: "Mackerel (85g)"), amount: String(localized: "nutrient.epa.amount.1", defaultValue: "760mg"), emoji: "🐡"), FoodSource(food: String(localized: "nutrient.epa.food.2", defaultValue: "Sardines (85g)"), amount: String(localized: "nutrient.epa.amount.2", defaultValue: "430mg"), emoji: "🐠"), FoodSource(food: String(localized: "nutrient.epa.food.3", defaultValue: "Herring (85g)"), amount: String(localized: "nutrient.epa.amount.3", defaultValue: "600mg"), emoji: "🐟")], deficiencySymptoms: ["joint_pain", "mood_swings", "skin_issues"]),
            Nutrient(key: "dha", name: String(localized: "nutrient.dha.name", defaultValue: "DHA (Omega-3)"), groupKey: .fattyAcids, emoji: "🧠", unit: "mg", tagline: String(localized: "nutrient.dha.tagline", defaultValue: "Brain & eye omega-3"), description: String(localized: "nutrient.dha.description", defaultValue: "Docosahexaenoic acid (DHA) is the most abundant omega-3 in brain tissue and retinal membranes. It is critical for cognitive function, visual acuity, and neuronal signalling. DHA needs increase during pregnancy and early childhood."), rdaMale: 500, rdaFemale: 500, foodSources: [FoodSource(food: String(localized: "nutrient.dha.food.0", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.dha.amount.0", defaultValue: "1020mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.dha.food.1", defaultValue: "Mackerel (85g)"), amount: String(localized: "nutrient.dha.amount.1", defaultValue: "1190mg"), emoji: "🐡"), FoodSource(food: String(localized: "nutrient.dha.food.2", defaultValue: "Sardines (85g)"), amount: String(localized: "nutrient.dha.amount.2", defaultValue: "630mg"), emoji: "🐠"), FoodSource(food: String(localized: "nutrient.dha.food.3", defaultValue: "Anchovies (30g)"), amount: String(localized: "nutrient.dha.amount.3", defaultValue: "310mg"), emoji: "🐟")], deficiencySymptoms: ["brain_fog", "mood_swings"]),
            Nutrient(key: "choline", name: String(localized: "nutrient.choline.name", defaultValue: "Choline"), groupKey: .fattyAcids, emoji: "🫀", unit: "mg", tagline: String(localized: "nutrient.choline.tagline", defaultValue: "Liver & brain essential"), description: String(localized: "nutrient.choline.description", defaultValue: "Choline is required for cell membrane structure (phosphatidylcholine), neurotransmitter synthesis (acetylcholine), methyl donation, and liver fat metabolism. Over 90% of people do not meet the adequate intake."), rdaMale: 550, rdaFemale: 425, foodSources: [FoodSource(food: String(localized: "nutrient.choline.food.0", defaultValue: "Beef liver (85g)"), amount: String(localized: "nutrient.choline.amount.0", defaultValue: "356mg"), emoji: "🥩"), FoodSource(food: String(localized: "nutrient.choline.food.1", defaultValue: "Eggs (2 large, 100g)"), amount: String(localized: "nutrient.choline.amount.1", defaultValue: "294mg"), emoji: "🥚"), FoodSource(food: String(localized: "nutrient.choline.food.2", defaultValue: "Salmon (85g)"), amount: String(localized: "nutrient.choline.amount.2", defaultValue: "77mg"), emoji: "🐟"), FoodSource(food: String(localized: "nutrient.choline.food.3", defaultValue: "Chicken breast (85g)"), amount: String(localized: "nutrient.choline.amount.3", defaultValue: "72mg"), emoji: "🍗")], deficiencySymptoms: ["fatigue", "brain_fog"]),
        ]
    }

    static func group(_ key: GroupKey) -> Group { groups.first { $0.key == key }! }
    static func nutrient(_ key: String) -> Nutrient? { nutrients.first { $0.key == key } }
    static func nutrients(in group: GroupKey) -> [Nutrient] { nutrients.filter { $0.groupKey == group } }

    /// Minerals are elements, not molecules — the periodic-table tile (symbol + atomic number).
    static let elements: [String: (symbol: String, number: Int)] = [
        "magnesium": ("Mg", 12), "iron": ("Fe", 26), "zinc": ("Zn", 30), "calcium": ("Ca", 20),
        "selenium": ("Se", 34), "iodine": ("I", 53), "potassium": ("K", 19), "phosphorus": ("P", 15),
    ]

    static func symptomLabel(_ key: String) -> String {
        switch key {
        case "fatigue": String(localized: "symptom.fatigue", defaultValue: "Fatigue")
        case "mood_swings": String(localized: "symptom.mood_swings", defaultValue: "Mood swings")
        case "joint_pain": String(localized: "symptom.joint_pain", defaultValue: "Joint pain")
        case "anxiety": String(localized: "symptom.anxiety", defaultValue: "Anxiety")
        case "insomnia": String(localized: "symptom.insomnia", defaultValue: "Insomnia")
        case "skin_issues": String(localized: "symptom.skin_issues", defaultValue: "Skin issues")
        case "brain_fog": String(localized: "symptom.brain_fog", defaultValue: "Brain fog")
        case "headaches": String(localized: "symptom.headaches", defaultValue: "Headaches")
        case "muscle_pain": String(localized: "symptom.muscle_pain", defaultValue: "Muscle pain")
        case "digestive": String(localized: "symptom.digestive", defaultValue: "Digestive discomfort")
        default: key.replacingOccurrences(of: "_", with: " ").capitalized
        }
    }
}

/// "Understanding the 3 macros" — the Expo `MACRO_EDUCATION`, in the member's language.
enum MacroEducation {
    struct Entry: Identifiable, Sendable {
        let key: String
        let title: String
        let emoji: String
        let tagline: String
        let why: String
        let bestSources: [String]
        let timing: String
        let myths: [String]
        var id: String { key }
    }

    static var entries: [Entry] {
        [
            Entry(key: "protein", title: String(localized: "macroEdu.protein.title", defaultValue: "Protein"), emoji: "🥩", tagline: String(localized: "macroEdu.protein.tagline", defaultValue: "Build, repair, and protect"), why: String(localized: "macroEdu.protein.why", defaultValue: "Protein is the building block of every cell in your body. We currently target 1.5g/kg/day for women and 1.8g/kg/day for men. It builds muscle, repairs tissue, supports hormones, and improves satiety."), bestSources: [String(localized: "macroEdu.protein.source.0", defaultValue: "Chicken breast"), String(localized: "macroEdu.protein.source.1", defaultValue: "Eggs"), String(localized: "macroEdu.protein.source.2", defaultValue: "Greek yogurt"), String(localized: "macroEdu.protein.source.3", defaultValue: "Salmon"), String(localized: "macroEdu.protein.source.4", defaultValue: "Lentils"), String(localized: "macroEdu.protein.source.5", defaultValue: "Cottage cheese")], timing: String(localized: "macroEdu.protein.timing", defaultValue: "Spread protein across all meals. Aim for 20-40g per meal. Post-workout is especially important."), myths: [String(localized: "macroEdu.protein.myth.0", defaultValue: "Myth: Too much protein damages kidneys (only true in existing kidney disease)"), String(localized: "macroEdu.protein.myth.1", defaultValue: "Myth: Plant protein is inferior (complete protein is achievable on plant-based diets)")]),
            Entry(key: "carbs", title: String(localized: "macroEdu.carbs.title", defaultValue: "Carbohydrates"), emoji: "🌾", tagline: String(localized: "macroEdu.carbs.tagline", defaultValue: "Your brain and muscles run on this"), why: String(localized: "macroEdu.carbs.why", defaultValue: "Carbohydrates are your primary energy source. Your brain alone uses 120g per day. Quality matters more than quantity - choose complex carbs with fiber over refined sugars."), bestSources: [String(localized: "macroEdu.carbs.source.0", defaultValue: "Sweet potato"), String(localized: "macroEdu.carbs.source.1", defaultValue: "Oats"), String(localized: "macroEdu.carbs.source.2", defaultValue: "Brown rice"), String(localized: "macroEdu.carbs.source.3", defaultValue: "Quinoa"), String(localized: "macroEdu.carbs.source.4", defaultValue: "Fruits"), String(localized: "macroEdu.carbs.source.5", defaultValue: "Legumes")], timing: String(localized: "macroEdu.carbs.timing", defaultValue: "Prioritise carbs around workouts. Reduce simple sugars in the evening. Keep fiber high throughout the day."), myths: [String(localized: "macroEdu.carbs.myth.0", defaultValue: "Myth: Carbs make you fat (excess calories do, not carbs specifically)"), String(localized: "macroEdu.carbs.myth.1", defaultValue: "Myth: You should eliminate carbs (brain needs glucose to function)")]),
            Entry(key: "fat", title: String(localized: "macroEdu.fat.title", defaultValue: "Fats"), emoji: "🥑", tagline: String(localized: "macroEdu.fat.tagline", defaultValue: "Hormones, brain, and vitamin absorption"), why: String(localized: "macroEdu.fat.why", defaultValue: "Dietary fat is essential for hormone production, brain function, and absorbing fat-soluble vitamins (A, D, E, K). Focus on unsaturated fats and omega-3s. Minimise trans fats."), bestSources: [String(localized: "macroEdu.fat.source.0", defaultValue: "Avocado"), String(localized: "macroEdu.fat.source.1", defaultValue: "Olive oil"), String(localized: "macroEdu.fat.source.2", defaultValue: "Salmon"), String(localized: "macroEdu.fat.source.3", defaultValue: "Walnuts"), String(localized: "macroEdu.fat.source.4", defaultValue: "Almonds"), String(localized: "macroEdu.fat.source.5", defaultValue: "Eggs")], timing: String(localized: "macroEdu.fat.timing", defaultValue: "Fat slows digestion - useful at breakfast and dinner, less ideal right before intense exercise."), myths: [String(localized: "macroEdu.fat.myth.0", defaultValue: "Myth: Fat makes you fat (excess calories do)"), String(localized: "macroEdu.fat.myth.1", defaultValue: "Myth: All saturated fat is bad (coconut and dairy fat behave differently)")]),
        ]
    }
}
