-- privacy_policy v9 — Apple Health / wearable data disclosed (iOS Devices screen).
--
-- WHY: the native iOS app reads Apple Health (incl. Apple Watch) on the member's phone and
-- posts daily values to `wearable-ingest`. The v8 notice deliberately did not describe
-- wearable data (Thryve was dropped from the Expo app the same day). Disclosure follows the
-- code: the app's Connect button stays disabled until the CURRENT APPROVED notice is v9+.
--
-- HOW: v9 = the live v8 rows (proven byte-identical to the app render by content_hash)
-- with six insertions per locale, applied with replace() on unique anchors that this
-- block ASSERTS occur exactly once. Nothing else in the wording changes.
--
-- STATE: inserted as `draft_pending_legal_review`, v8 NOT superseded. Members keep seeing v8
-- (iOS reads approved + not superseded; the Expo app renders its local copy; MEMBERS does
-- not read notices). Approval = the operator's explicit word, then:
--   update consent_definitions set superseded_at = now()
--    where consent_key = 'privacy_policy' and version = 'v8' and superseded_at is null;
--   update consent_definitions
--      set review_status = 'approved', approved_by = '<operator>', approved_at = now(),
--          effective_from = now(), approval_note = '<note>'
--    where consent_key = 'privacy_policy' and version = 'v9';
-- Re-running this file is a no-op once the v9 rows exist.

do $mig$
declare
  v8_en text;
  v8_fr text;
  v9_en text;
  v9_fr text;
  procedure_check int;

  -- English anchors (each must occur exactly once in v8 en) ---------------------------------
  en_a1 constant text := '- If you use voice input, the recording is transcribed by Infomaniak and then handled like anything else you log.';
  en_a2 constant text := '- Voice recordings — where you use voice input, the audio you record, and the text transcribed from it. See section 9.';
  en_a3 constant text := '- Generated by the service — scores';
  en_a4 constant text := '- To store and analyse your health information so the service can exist at all — meal, check-in, symptom and voice data. Basis: your explicit consent to health-data processing (GDPR Art. 9(2)(a); FADP Art. 6(7)(a)), on top of the contract basis above.';
  en_a5 constant text := '### 10. Who inside FunctionAlps can see your data';
  en_a6 constant text := '- Voice recordings — the audio is retained only as long as needed to produce and verify the transcript, and is then deleted; the transcript follows the entry it belongs to.';

  en_i1 constant text := E'\n- If you connect Apple Health on your iPhone, we read the readings you allow — steps, sleep, heart rate and similar, including what your Apple Watch recorded — and nothing is written back. That is described in section 9a.';
  en_i2 constant text := E'\n- Wearable data — if you connect Apple Health on your iPhone (including what an Apple Watch or another device has written there): steps, distance, energy burned, exercise minutes and workouts; sleep and its stages; heart rate, resting heart rate and heart-rate variability; breathing rate, blood oxygen and VO₂ max; and weight. Each reading carries the day or time it was recorded and the device category it came from. See section 9a.';
  en_i3 constant text := E'- From Apple Health — only if you choose to connect it, and then only the categories you allow in Apple’s permission sheet. The app reads them on your phone; Apple sends us nothing and receives nothing from us.\n';
  en_i4 constant text := E'\n- To bring in the readings from Apple Health that you choose to share, and to read them alongside what you log — wearable data. Basis: that same explicit consent to health-data processing, together with your separate choice to connect, which you can undo at any time (section 9a).';
  en_i5 constant text := E'### 9a. Apple Health and wearables\n\nIf you choose to connect Apple Health in the app, the app reads the categories you allow in Apple’s permission sheet — including what your Apple Watch, or any other device that syncs into Apple Health, has recorded there — and sends them to your FunctionAlps record. It only reads: it never writes anything to Apple Health, and Apple is not a party to the transfer.\n\nThe readings are reduced on your phone before they are sent: one value per day for each category (your steps, your resting heart rate, how long you slept and in which stages, and so on) and one entry per workout. Those daily values are stored with the day they belong to and with a marker saying they came from Apple Health, and they are shown to you and to your practitioner next to your meals and check-ins, so that your body’s response can be read together with what you logged. They may be used in the scores and patterns the service computes for you, under the rules in section 8.\n\nWearable readings are health data and are covered by the explicit consent described in section 7. Like everything else you log, they are never sent to OpenAI, Google, Anthropic or any other general-purpose AI provider.\n\nYou can stop the connection at any time on the Devices screen in the app; the phone then stops sending. You can also withdraw the app’s permission for any category, or for everything, in Settings → Health → Data Access & Devices on your iPhone. Readings already sent stay in your record under the rules in section 13 and are deleted with everything else when you delete your account.\n\n';
  en_i6 constant text := E'\n- Wearable readings — while your account is active, like the rest of your record; the raw submissions from your phone are kept alongside them so that a value can always be traced back to what the phone sent.';

  -- French anchors -------------------------------------------------------------------------
  fr_a1 constant text := '- Si vous utilisez la saisie vocale, l’enregistrement est transcrit par Infomaniak puis traité comme toute autre saisie.';
  fr_a2 constant text := '- Enregistrements vocaux — lorsque vous utilisez la saisie vocale, l’audio enregistré et le texte qui en est transcrit. Voir la section 9.';
  fr_a3 constant text := '- Générées par le service — scores';
  fr_a4 constant text := '- Conserver et analyser vos informations de santé, sans quoi le service ne peut exister — données de repas, de bilan, de symptômes et vocales. Base : votre consentement explicite au traitement des données de santé (art. 9 par. 2 let. a RGPD ; art. 6 al. 7 let. a LPD), en sus de la base contractuelle ci-dessus.';
  fr_a5 constant text := '### 10. Qui, chez FunctionAlps, peut voir vos données';
  fr_a6 constant text := '- Enregistrements vocaux — l’audio n’est conservé que le temps nécessaire à la production et à la vérification de la transcription, puis supprimé ; la transcription suit l’élément auquel elle se rattache.';

  fr_i1 constant text := E'\n- Si vous connectez Apple Santé sur votre iPhone, nous lisons les mesures que vous autorisez — pas, sommeil, fréquence cardiaque et données similaires, y compris ce que votre Apple Watch a enregistré — et rien n’y est écrit en retour. Voir la section 9a.';
  fr_i2 constant text := E'\n- Données d’objets connectés — si vous connectez Apple Santé sur votre iPhone (y compris ce qu’une Apple Watch ou un autre appareil y a inscrit) : pas, distance, énergie dépensée, minutes d’exercice et séances de sport ; sommeil et ses phases ; fréquence cardiaque, fréquence cardiaque au repos et variabilité de la fréquence cardiaque ; fréquence respiratoire, saturation en oxygène et VO₂ max ; et poids. Chaque mesure porte le jour ou l’heure de son enregistrement et la catégorie d’appareil dont elle provient. Voir la section 9a.';
  fr_i3 constant text := E'- D’Apple Santé — uniquement si vous choisissez de le connecter, et alors seulement pour les catégories que vous autorisez dans la fenêtre d’autorisation d’Apple. L’application les lit sur votre téléphone ; Apple ne nous transmet rien et ne reçoit rien de nous.\n';
  fr_i4 constant text := E'\n- Importer les mesures d’Apple Santé que vous choisissez de partager, et les lire aux côtés de vos saisies — données d’objets connectés. Base : le même consentement explicite au traitement des données de santé, joint à votre choix distinct de connecter l’appareil, que vous pouvez annuler à tout moment (section 9a).';
  fr_i5 constant text := E'### 9a. Apple Santé et objets connectés\n\nSi vous choisissez de connecter Apple Santé dans l’application, celle-ci lit les catégories que vous autorisez dans la fenêtre d’autorisation d’Apple — y compris ce que votre Apple Watch, ou tout autre appareil synchronisé avec Apple Santé, y a enregistré — et les transmet à votre dossier FunctionAlps. Elle ne fait que lire : elle n’écrit jamais rien dans Apple Santé, et Apple n’est pas partie au transfert.\n\nLes mesures sont réduites sur votre téléphone avant l’envoi : une valeur par jour et par catégorie (vos pas, votre fréquence cardiaque au repos, la durée de votre sommeil et ses phases, etc.) et une entrée par séance de sport. Ces valeurs quotidiennes sont conservées avec le jour auquel elles se rapportent et avec la mention qu’elles proviennent d’Apple Santé ; elles vous sont présentées, ainsi qu’à votre praticienne, à côté de vos repas et de vos bilans, afin que la réaction de votre corps puisse être lue avec ce que vous avez enregistré. Elles peuvent entrer dans les scores et tendances que le service calcule pour vous, selon les règles de la section 8.\n\nLes mesures d’objets connectés sont des données de santé et relèvent du consentement explicite décrit à la section 7. Comme tout ce que vous enregistrez, elles ne sont jamais transmises à OpenAI, Google, Anthropic ni à aucun autre fournisseur d’IA généraliste.\n\nVous pouvez interrompre la connexion à tout moment depuis l’écran Appareils de l’application ; le téléphone cesse alors d’envoyer. Vous pouvez aussi retirer l’autorisation de l’application pour une catégorie, ou pour l’ensemble, dans Réglages → Santé → Accès aux données et appareils sur votre iPhone. Les mesures déjà transmises restent dans votre dossier selon les règles de la section 13 et sont supprimées avec le reste lorsque vous supprimez votre compte.\n\n';
  fr_i6 constant text := E'\n- Mesures d’objets connectés — tant que votre compte est actif, comme le reste de votre dossier ; les envois bruts de votre téléphone sont conservés avec elles afin qu’une valeur puisse toujours être rattachée à ce que le téléphone a transmis.';

  function_count int;
begin
  if exists (select 1 from public.consent_definitions where consent_key = 'privacy_policy' and version = 'v9') then
    raise notice 'privacy_policy v9 already present — nothing to do';
    return;
  end if;

  select body_md into v8_en from public.consent_definitions
   where consent_key = 'privacy_policy' and version = 'v8' and locale = 'en' and superseded_at is null and review_status = 'approved';
  select body_md into v8_fr from public.consent_definitions
   where consent_key = 'privacy_policy' and version = 'v8' and locale = 'fr' and superseded_at is null and review_status = 'approved';
  if v8_en is null or v8_fr is null then
    raise exception 'privacy_policy v8 (approved, current) not found for both locales';
  end if;

  -- Every anchor exactly once, or stop before writing anything.
  foreach procedure_check in array array[
    (length(v8_en) - length(replace(v8_en, en_a1, ''))) / length(en_a1),
    (length(v8_en) - length(replace(v8_en, en_a2, ''))) / length(en_a2),
    (length(v8_en) - length(replace(v8_en, en_a3, ''))) / length(en_a3),
    (length(v8_en) - length(replace(v8_en, en_a4, ''))) / length(en_a4),
    (length(v8_en) - length(replace(v8_en, en_a5, ''))) / length(en_a5),
    (length(v8_en) - length(replace(v8_en, en_a6, ''))) / length(en_a6),
    (length(v8_fr) - length(replace(v8_fr, fr_a1, ''))) / length(fr_a1),
    (length(v8_fr) - length(replace(v8_fr, fr_a2, ''))) / length(fr_a2),
    (length(v8_fr) - length(replace(v8_fr, fr_a3, ''))) / length(fr_a3),
    (length(v8_fr) - length(replace(v8_fr, fr_a4, ''))) / length(fr_a4),
    (length(v8_fr) - length(replace(v8_fr, fr_a5, ''))) / length(fr_a5),
    (length(v8_fr) - length(replace(v8_fr, fr_a6, ''))) / length(fr_a6)
  ] loop
    if procedure_check <> 1 then
      raise exception 'privacy_policy v9: an anchor does not occur exactly once in v8 (count %)', procedure_check;
    end if;
  end loop;

  v9_en := v8_en;
  v9_en := replace(v9_en, en_a1, en_a1 || en_i1);
  v9_en := replace(v9_en, en_a2, en_a2 || en_i2);
  v9_en := replace(v9_en, en_a3, en_i3 || en_a3);
  v9_en := replace(v9_en, en_a4, en_a4 || en_i4);
  v9_en := replace(v9_en, en_a5, en_i5 || en_a5);
  v9_en := replace(v9_en, en_a6, en_a6 || en_i6);

  v9_fr := v8_fr;
  v9_fr := replace(v9_fr, fr_a1, fr_a1 || fr_i1);
  v9_fr := replace(v9_fr, fr_a2, fr_a2 || fr_i2);
  v9_fr := replace(v9_fr, fr_a3, fr_i3 || fr_a3);
  v9_fr := replace(v9_fr, fr_a4, fr_a4 || fr_i4);
  v9_fr := replace(v9_fr, fr_a5, fr_i5 || fr_a5);
  v9_fr := replace(v9_fr, fr_a6, fr_a6 || fr_i6);

  insert into public.consent_definitions
    (consent_key, version, locale, title, summary, body_md, required, display_order, legal_basis, doc_kind, basis, review_status, approval_note)
  select consent_key, 'v9', locale, title, summary,
         case locale when 'en' then v9_en else v9_fr end,
         required, display_order, legal_basis, doc_kind, basis,
         'draft_pending_legal_review',
         'v9 = v8 + Apple Health / wearable data (§1, §4, §5, §6, §9a, §13). Drafted 2026-09-04 for the iOS Devices screen; awaiting the operator''s approval.'
    from public.consent_definitions
   where consent_key = 'privacy_policy' and version = 'v8' and superseded_at is null and review_status = 'approved';

  get diagnostics function_count = row_count;
  if function_count <> 2 then
    raise exception 'privacy_policy v9: expected 2 rows inserted, got %', function_count;
  end if;
  raise notice 'privacy_policy v9 drafted (en + fr), v8 still current';
end
$mig$;
