-- privacy_policy v11 + terms_of_use v8 (owner's call 2026-09-14: "update privacy notice and terms and push to the URLs").
--
-- Review findings of 2026-09-14 folded in (both locales, anchor-checked edits of the live v10 / v7 texts):
--   Privacy v11: Sign in with Apple named wherever Google was (§3, §4, §5, §11; Apple's private relay address);
--   push notifications (device token in §4 technical data, Apple as recipient in §11, no health data in the text);
--   Vercel as the web host (§11, §12); the Apple Health categories the relay now reads (flights climbed, body-fat
--   percentage, body temperature, §4); the link/unlink/delete log is "one you can ask us for" until the app shows it (§9a).
--   Terms v8: wearables named in what the service is (§4) and what it does with what you log (§8); linking a vendor
--   account as a third-party choice (§21).
-- Rows are cloned from the current v10 / v7 rows (each anchor must occur exactly once), which are then superseded.
-- Members are asked to accept once, on whichever surface they open next (Terms §22 / Privacy §20). The app's
-- WearableDisclosure gate (v10+) stays satisfied.
create or replace function pg_temp.fa_apply_edits(body text, anchors text[], replacements text[]) returns text language plpgsql as $f$
declare i int; c int;
begin
  for i in 1 .. array_length(anchors, 1) loop
    c := (length(body) - length(replace(body, anchors[i], ''))) / length(anchors[i]);
    if c <> 1 then raise exception 'anchor % occurs % times: %', i, c, left(anchors[i], 60); end if;
    body := replace(body, anchors[i], replacements[i]);
  end loop;
  return body;
end $f$;
do $mig$
declare n int;
begin
  if exists (select 1 from public.consent_definitions where (consent_key = 'privacy_policy' and version = 'v11') or (consent_key = 'terms_of_use' and version = 'v8')) then
    raise exception 'privacy_policy v11 / terms_of_use v8 already exist';
  end if;
  insert into public.consent_definitions (consent_key, version, locale, title, summary, body_md, required, display_order, legal_basis, doc_kind, basis, review_status, approved_by, approved_at, effective_from, approval_note)
  select consent_key, 'v11', locale, title, summary,
         case locale when 'en' then pg_temp.fa_apply_edits(body_md, array[E'for example Google, if you sign in with a Google account', E'(or, if you sign in with Google, an identifier from Google rather than a password)', E'breathing rate, blood oxygen and VO₂ max; and weight.', E'error and diagnostic logs, and the internet protocol address seen when you connect.', E'- From Google — only if you choose to sign in with Google, and then only the identifier and email address needed to authenticate you.', E'Every link, unlink and deletion is recorded in a log you can read in the app.', E'- Google — only if you choose to sign in with Google, and then only for authenticating you.', E'and Switzerland is recognised as adequate by the European Commission.'], array[E'for example Google or Apple, if you sign in with a Google or Apple account', E'(or, if you sign in with Google or with Apple, an identifier from that provider rather than a password; Apple may give us a private relay address instead of your own email address)', E'breathing rate, blood oxygen and VO₂ max; weight, body-fat percentage and body temperature; and flights climbed.', E'error and diagnostic logs, and the internet protocol address seen when you connect. If you allow notifications on your phone, also the device token Apple assigns to it, so that we can send them (see section 11); the text of a notification never contains health data.', E'- From Google or Apple — only if you choose to sign in with one of them, and then only the identifier and email address needed to authenticate you (Apple may provide a private relay address).', E'Every link, unlink and deletion is recorded in a log that you can ask us for at any time.', E'- Google or Apple — only if you choose to sign in with one of them, and then only for authenticating you.\n- Apple — for push notifications, if you allow them on your iPhone: Apple delivers the notification and receives only your device token; the text never contains health data.\n- Vercel — hosts the web app and the members dashboard and delivers their files through a global network; it sees the technical data of your connection, including your IP address, and nothing you log.', E'and Switzerland is recognised as adequate by the European Commission. The web app’s files are delivered by Vercel’s global network, which sees only your connection data; everything you log is stored in the EU and Switzerland as described.'])
                     else pg_temp.fa_apply_edits(body_md, array[E'par exemple Google, si vous vous connectez avec un compte Google', E'(ou, si vous vous connectez avec Google, un identifiant fourni par Google au lieu d’un mot de passe)', E'fréquence respiratoire, saturation en oxygène et VO₂ max ; et poids.', E'journaux d’erreur et de diagnostic, et l’adresse IP observée lors de votre connexion.', E'- De Google — uniquement si vous choisissez la connexion Google, et alors seulement l’identifiant et l’adresse électronique nécessaires à votre authentification.', E'Chaque liaison, dissociation et suppression est inscrite dans un journal que vous pouvez consulter dans l’application.', E'- Google — uniquement si vous choisissez la connexion Google, et alors seulement pour vous authentifier.', E'et la Suisse bénéficie d’une décision d’adéquation de la Commission européenne.'], array[E'par exemple Google ou Apple, si vous vous connectez avec un compte Google ou Apple', E'(ou, si vous vous connectez avec Google ou avec Apple, un identifiant fourni par ce prestataire au lieu d’un mot de passe ; Apple peut nous transmettre une adresse relais privée au lieu de votre propre adresse électronique)', E'fréquence respiratoire, saturation en oxygène et VO₂ max ; poids, pourcentage de masse grasse et température corporelle ; et étages gravis.', E'journaux d’erreur et de diagnostic, et l’adresse IP observée lors de votre connexion. Si vous autorisez les notifications sur votre téléphone, également le jeton d’appareil attribué par Apple, qui nous permet de les envoyer (voir la section 11) ; le texte d’une notification ne contient jamais de données de santé.', E'- De Google ou d’Apple — uniquement si vous choisissez l’une de ces connexions, et alors seulement l’identifiant et l’adresse électronique nécessaires à votre authentification (Apple peut fournir une adresse relais privée).', E'Chaque liaison, dissociation et suppression est inscrite dans un journal que vous pouvez nous demander à tout moment.', E'- Google ou Apple — uniquement si vous choisissez l’une de ces connexions, et alors seulement pour vous authentifier.\n- Apple — pour les notifications, si vous les autorisez sur votre iPhone : Apple délivre la notification et ne reçoit que le jeton de votre appareil ; le texte ne contient jamais de données de santé.\n- Vercel — héberge l’application web et le tableau de bord membres et en distribue les fichiers par un réseau mondial ; il voit les données techniques de votre connexion, dont votre adresse IP, et rien de ce que vous enregistrez.', E'et la Suisse bénéficie d’une décision d’adéquation de la Commission européenne. Les fichiers de l’application web sont distribués par le réseau mondial de Vercel, qui ne voit que vos données de connexion ; tout ce que vous enregistrez est conservé dans l’UE et en Suisse comme décrit.']) end,
         required, display_order, legal_basis, doc_kind, basis,
         'approved', 'Thomas Convent — operator, FunctionAlps', now(), now(),
         'v11 = v10 + Sign in with Apple, push notifications, Vercel, the newer Apple Health categories, the link-log wording. Review of 2026-09-14; operator''s call 2026-09-14 (qualified legal review still to come).'
    from public.consent_definitions where consent_key = 'privacy_policy' and version = 'v10' and superseded_at is null and review_status = 'approved';
  get diagnostics n = row_count;
  if n <> 2 then raise exception 'privacy_policy v11: expected 2 rows inserted, got %', n; end if;
  insert into public.consent_definitions (consent_key, version, locale, title, summary, body_md, required, display_order, legal_basis, doc_kind, basis, review_status, approved_by, approved_at, effective_from, approval_note)
  select consent_key, 'v8', locale, title, summary,
         case locale when 'en' then pg_temp.fa_apply_edits(body_md, array[E'It lets you log meals, check-ins, symptoms and supplements, it derives nutritional estimates and scores from what you log,', E'Answers you give in a website assessment are handled the same way.', E'that relationship is governed by their terms, and we are not responsible for their services or content.'], array[E'It lets you log meals, check-ins, symptoms and supplements and, if you choose, brings in readings from Apple Health or from a wearable account you link (Oura, WHOOP, Polar, Garmin, Withings, Suunto or Google Fitbit); it derives nutritional estimates and scores from what you log,', E'Answers you give in a website assessment are handled the same way, and so are readings from Apple Health or from a linked wearable account; the Privacy Policy, section 9a, describes them.', E'that relationship is governed by their terms, and we are not responsible for their services or content.\n\nLinking a wearable account is such a choice: your account with the vendor stays governed by the vendor’s own terms, we receive only the readings you authorise there, and you can end the link at any time in the app or at the vendor.'])
                     else pg_temp.fa_apply_edits(body_md, array[E'Elle vous permet d’enregistrer vos repas, vos bilans quotidiens, vos symptômes et vos compléments ; elle en déduit', E'Les réponses données dans un questionnaire du site internet sont traitées de la même manière.', E'cette relation est régie par les conditions de ce tiers, et nous ne répondons ni de ses services ni de ses contenus.'], array[E'Elle vous permet d’enregistrer vos repas, vos bilans quotidiens, vos symptômes et vos compléments et, si vous le choisissez, d’y joindre les mesures d’Apple Santé ou d’un compte d’objet connecté que vous liez (Oura, WHOOP, Polar, Garmin, Withings, Suunto ou Google Fitbit) ; elle en déduit', E'Les réponses données dans un questionnaire du site internet sont traitées de la même manière, tout comme les mesures provenant d’Apple Santé ou d’un compte d’objet connecté lié ; la Déclaration de confidentialité, section 9a, les décrit.', E'cette relation est régie par les conditions de ce tiers, et nous ne répondons ni de ses services ni de ses contenus.\n\nLier un compte d’objet connecté relève de ce choix : votre compte chez le fournisseur reste régi par ses propres conditions, nous ne recevons que les mesures que vous y autorisez, et vous pouvez mettre fin à la liaison à tout moment dans l’application ou chez le fournisseur.']) end,
         required, display_order, legal_basis, doc_kind, basis,
         'approved', 'Thomas Convent — operator, FunctionAlps', now(), now(),
         'v8 = v7 + wearables (Apple Health and linked vendor accounts) in §4, §8 and §21. Review of 2026-09-14; operator''s call 2026-09-14 (qualified legal review still to come).'
    from public.consent_definitions where consent_key = 'terms_of_use' and version = 'v7' and superseded_at is null and review_status = 'approved';
  get diagnostics n = row_count;
  if n <> 2 then raise exception 'terms_of_use v8: expected 2 rows inserted, got %', n; end if;
  update public.consent_definitions set superseded_at = now() where consent_key = 'privacy_policy' and version = 'v10' and superseded_at is null;
  update public.consent_definitions set superseded_at = now() where consent_key = 'terms_of_use' and version = 'v7' and superseded_at is null;
  raise notice 'privacy_policy v11 + terms_of_use v8 current (en + fr); v10 / v7 superseded';
end
$mig$;
drop function pg_temp.fa_apply_edits(text, text[], text[]);
